# Generated by Django 5.1.7 on 2025-05-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneFourSeven', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchesofanevent',
            old_name='Status',
            new_name='status_code',
        ),
        migrations.RenameIndex(
            model_name='matchesofanevent',
            new_name='match_logical_key_idx',
            old_name='oneFourSeve_Event_i_79b2ab_idx',
        ),
        migrations.RenameIndex(
            model_name='matchesofanevent',
            new_name='match_player1_idx',
            old_name='oneFourSeve_Player1_b8eed4_idx',
        ),
        migrations.RenameIndex(
            model_name='matchesofanevent',
            new_name='match_player2_idx',
            old_name='oneFourSeve_Player2_f14e55_idx',
        ),
        migrations.RenameIndex(
            model_name='matchesofanevent',
            new_name='match_api_id_idx',
            old_name='oneFourSeve_api_mat_97f13f_idx',
        ),
        migrations.AlterField(
            model_name='event',
            name='AgeGroup',
            field=models.CharField(blank=True, help_text='Age category (e.g., O (Open), U21). Consider defining choices if values are fixed.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='Sex',
            field=models.CharField(blank=True, help_text='Gender category (e.g., Men, Women, Mixed). Consider defining choices if values are fixed.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='Stage',
            field=models.CharField(blank=True, help_text='Event stage (e.g., F (Finals), Q (Qualifying)). Consider defining choices if values are fixed.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='matchesofanevent',
            name='api_match_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Match ID from external API (snooker.org). This is NOT the primary key.', null=True),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='ID',
            field=models.BigIntegerField(help_text="Ranking entry ID from API (used as PK; ensure it's stable and unique)", primary_key=True, serialize=False),
        ),
    ]
