# Generated by Django 5.1.7 on 2025-08-07 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneFourSeven', '0003_add_ranking_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Round', models.IntegerField(help_text='Round number from API')),
                ('RoundName', models.CharField(blank=True, help_text="Display name for the round (e.g., 'Round 1', 'Final')", max_length=100, null=True)),
                ('MainEvent', models.IntegerField(blank=True, help_text='Main event ID from API', null=True)),
                ('Distance', models.IntegerField(help_text="Frames needed to win the match (e.g., 6 for 'best of 11')")),
                ('NumLeft', models.IntegerField(blank=True, help_text='Number of players left in the tournament at this round', null=True)),
                ('NumMatches', models.IntegerField(blank=True, help_text='Number of matches in this round', null=True)),
                ('Note', models.TextField(blank=True, help_text='Additional notes about the round', null=True)),
                ('ValueType', models.CharField(blank=True, help_text="Value type from API (e.g., 'SM')", max_length=10, null=True)),
                ('Rank', models.IntegerField(blank=True, help_text='Ranking points available', null=True)),
                ('Money', models.DecimalField(blank=True, decimal_places=2, help_text='Prize money for this round', max_digits=10, null=True)),
                ('SeedGetsHalf', models.IntegerField(blank=True, help_text='Whether seed gets half points/money', null=True)),
                ('ActualMoney', models.DecimalField(blank=True, decimal_places=2, help_text='Actual prize money after conversions', max_digits=10, null=True)),
                ('Currency', models.CharField(blank=True, help_text="Currency code (e.g., 'GBP', 'USD')", max_length=3, null=True)),
                ('ConversionRate', models.DecimalField(blank=True, decimal_places=6, help_text='Currency conversion rate', max_digits=10, null=True)),
                ('Points', models.IntegerField(blank=True, help_text='Ranking points for this round', null=True)),
                ('SeedPoints', models.IntegerField(blank=True, help_text='Seed points for this round', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Event', models.ForeignKey(help_text='The tournament this round belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='round_details', to='oneFourSeven.event')),
            ],
            options={
                'verbose_name': 'Round Details',
                'verbose_name_plural': 'Round Details',
                'ordering': ['Event__Season', 'Event__StartDate', 'Round'],
                'indexes': [models.Index(fields=['Event', 'Round'], name='oneFourSeve_Event_i_554760_idx'), models.Index(fields=['Event'], name='oneFourSeve_Event_i_36e35a_idx')],
                'unique_together': {('Event', 'Round')},
            },
        ),
    ]
