# Generated by Django 5.1.7 on 2025-08-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneFourSeven', '0004_rounddetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_match_id', models.IntegerField(help_text='Original match ID from snooker.org API')),
                ('event_id', models.IntegerField(blank=True, help_text='Event ID from snooker.org API', null=True)),
                ('event_name', models.CharField(blank=True, help_text='Event/Tournament name', max_length=200, null=True)),
                ('round_number', models.IntegerField(blank=True, help_text='Round number in the tournament', null=True)),
                ('match_number', models.IntegerField(blank=True, help_text='Match number within the round', null=True)),
                ('player1_id', models.IntegerField(blank=True, help_text='Player 1 ID from snooker.org', null=True)),
                ('player2_id', models.IntegerField(blank=True, help_text='Player 2 ID from snooker.org', null=True)),
                ('player1_name', models.CharField(blank=True, help_text='Player 1 name', max_length=100, null=True)),
                ('player2_name', models.CharField(blank=True, help_text='Player 2 name', max_length=100, null=True)),
                ('score1', models.IntegerField(blank=True, help_text='Player 1 score/frames won', null=True)),
                ('score2', models.IntegerField(blank=True, help_text='Player 2 score/frames won', null=True)),
                ('winner_id', models.IntegerField(blank=True, help_text='Winner player ID (if match is finished)', null=True)),
                ('status', models.IntegerField(choices=[(0, 'Scheduled'), (1, 'Live'), (2, 'On Break'), (3, 'Finished')], default=0, help_text='Current match status')),
                ('scheduled_date', models.DateTimeField(blank=True, help_text='Scheduled start date and time', null=True)),
                ('tour_type', models.CharField(choices=[('main', 'Main Tour'), ('womens', 'Womens Tour'), ('seniors', 'Seniors Tour'), ('other', 'Other Tours'), ('all', 'All Tours')], default='main', help_text='Tour type this match belongs to', max_length=10)),
                ('raw_data', models.TextField(blank=True, help_text='Raw JSON data from snooker.org API', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Upcoming Match',
                'verbose_name_plural': 'Upcoming Matches',
                'ordering': ['scheduled_date', 'round_number', 'match_number'],
                'indexes': [models.Index(fields=['tour_type', 'scheduled_date'], name='oneFourSeve_tour_ty_4132c6_idx'), models.Index(fields=['status', 'scheduled_date'], name='oneFourSeve_status_b99d31_idx'), models.Index(fields=['event_id', 'round_number'], name='oneFourSeve_event_i_39cf64_idx'), models.Index(fields=['created_at'], name='oneFourSeve_created_c2371f_idx')],
            },
        ),
    ]
