# Generated by Django 5.1.7 on 2025-11-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneFourSeven', '0005_upcomingmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Photo',
            field=models.URLField(blank=True, help_text='Player photo URL from snooker.org', max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='PlayerMatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_match_id', models.BigIntegerField(help_text='Match ID from API')),
                ('player_id', models.IntegerField(db_index=True, help_text='Player ID this match belongs to')),
                ('event_id', models.IntegerField(blank=True, help_text='Tournament/Event ID', null=True)),
                ('event_name', models.CharField(blank=True, help_text='Tournament name (denormalized for faster display)', max_length=255, null=True)),
                ('round_number', models.IntegerField(blank=True, null=True)),
                ('round_name', models.CharField(blank=True, help_text="Round name like 'Final', 'Semi-Final'", max_length=100, null=True)),
                ('player1_id', models.IntegerField(blank=True, null=True)),
                ('player1_name', models.CharField(blank=True, max_length=255, null=True)),
                ('score1', models.IntegerField(blank=True, null=True)),
                ('player2_id', models.IntegerField(blank=True, null=True)),
                ('player2_name', models.CharField(blank=True, max_length=255, null=True)),
                ('score2', models.IntegerField(blank=True, null=True)),
                ('winner_id', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(default=0, help_text='0=Scheduled, 1=Running, 2=OnBreak, 3=Finished')),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('season', models.IntegerField(blank=True, help_text='Season year (e.g. 2024 for 2024/2025 season)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Player Match History',
                'verbose_name_plural': 'Player Match Histories',
                'ordering': ['-scheduled_date', '-start_date'],
                'indexes': [models.Index(fields=['player_id', '-scheduled_date'], name='oneFourSeve_player__ab3aca_idx'), models.Index(fields=['player_id', 'season'], name='oneFourSeve_player__022e6c_idx'), models.Index(fields=['status', 'scheduled_date'], name='oneFourSeve_status_8dc4f3_idx'), models.Index(fields=['api_match_id'], name='oneFourSeve_api_mat_d8b0cc_idx')],
                'unique_together': {('api_match_id', 'player_id')},
            },
        ),
    ]
