# Generated by Django 5.1.7 on 2026-03-24 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneFourSeven', '0008_devicetoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherTourEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snooker_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('tour', models.CharField(max_length=50)),
                ('season', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Other Tour Event',
                'verbose_name_plural': 'Other Tour Events',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='OtherTourPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snooker_id', models.IntegerField(db_index=True, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Other Tour Player',
                'verbose_name_plural': 'Other Tour Players',
            },
        ),
        migrations.CreateModel(
            name='OtherTourMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snooker_id', models.IntegerField(db_index=True, unique=True)),
                ('round', models.IntegerField()),
                ('number', models.IntegerField()),
                ('player1_id', models.IntegerField(blank=True, null=True)),
                ('player2_id', models.IntegerField(blank=True, null=True)),
                ('player1_name', models.CharField(default='TBD', max_length=150)),
                ('player2_name', models.CharField(default='TBD', max_length=150)),
                ('player1_nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('player2_nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('score1', models.IntegerField(blank=True, null=True)),
                ('score2', models.IntegerField(blank=True, null=True)),
                ('winner_id', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(default=0)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='oneFourSeven.othertourevent')),
            ],
            options={
                'verbose_name': 'Other Tour Match',
                'verbose_name_plural': 'Other Tour Matches',
                'ordering': ['round', 'number'],
                'unique_together': {('event', 'round', 'number')},
            },
        ),
    ]
