# Generated by Django 5.1.7 on 2026-04-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneFourSeven', '0010_devicetoken_push_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='H2HCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_id', models.IntegerField()),
                ('player2_id', models.IntegerField()),
                ('total', models.IntegerField()),
                ('p1_wins', models.IntegerField()),
                ('p2_wins', models.IntegerField()),
                ('raw_json', models.TextField()),
                ('fetched_at', models.DateTimeField()),
            ],
            options={
                'unique_together': {('player1_id', 'player2_id')},
            },
        ),
    ]
