# Generated by Django 5.1.7 on 2026-04-06 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneFourSeven', '0011_h2h_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenturyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('career_total', models.IntegerField(default=0)),
                ('career_147s', models.IntegerField(default=0)),
                ('season_current', models.IntegerField(default=0)),
                ('season_prev1', models.IntegerField(default=0)),
                ('season_prev2', models.IntegerField(default=0)),
                ('season_label', models.CharField(max_length=10)),
                ('scraped_at', models.DateTimeField()),
                ('player', models.ForeignKey(blank=True, help_text='Linked Player row — null if name match failed', null=True, on_delete=django.db.models.deletion.SET_NULL, to='oneFourSeven.player')),
            ],
            options={
                'unique_together': {('player_name', 'season_label')},
            },
        ),
    ]
