# Generated by Django 5.1.7 on 2026-04-14 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oneFourSeven', '0014_matchcomment_commentlike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchprediction',
            old_name='match_api_id',
            new_name='match_db_id',
        ),
        migrations.AlterUniqueTogether(
            name='matchprediction',
            unique_together={('device_id', 'match_db_id')},
        ),
    ]
