# Generated by Django 5.1.7 on 2026-04-14 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oneFourSeven', '0015_rename_match_api_id_matchprediction_match_db_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchcomment',
            old_name='match_api_id',
            new_name='match_db_id',
        ),
    ]
