# Generated by Django 5.1.7 on 2026-04-14 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oneFourSeven', '0017_deduplicate_player_match_history'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playermatchhistory',
            unique_together={('player_id', 'event_id', 'round_number', 'player1_id', 'player2_id')},
        ),
    ]
