# Generated by Django 5.1.7 on 2026-04-16 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneFourSeven', '0018_alter_playermatchhistory_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchFrameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_number', models.IntegerField()),
                ('player1_points', models.IntegerField()),
                ('player2_points', models.IntegerField()),
                ('player1_break', models.IntegerField(blank=True, null=True)),
                ('player2_break', models.IntegerField(blank=True, null=True)),
                ('winner', models.IntegerField()),
                ('source', models.CharField(default='cuetracker', max_length=50)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frame_scores_ct', to='oneFourSeven.matchesofanevent')),
            ],
            options={
                'verbose_name': 'Match Frame Score',
                'verbose_name_plural': 'Match Frame Scores',
                'ordering': ['frame_number'],
                'unique_together': {('match', 'frame_number')},
            },
        ),
    ]
