# Generated by Django 5.1.7 on 2026-04-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneFourSeven', '0019_matchframescore'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ct_slug',
            field=models.CharField(blank=True, help_text="CueTracker URL slug for this player. null = not yet tried. 'NOT_FOUND' = confirmed absent on CueTracker. Any other value = working slug used directly (no re-derivation).", max_length=150, null=True),
        ),
    ]
