# Generated by Django 5.1.7 on 2026-04-16 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneFourSeven', '0020_player_ct_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCareerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ct_frames_played', models.IntegerField(blank=True, null=True)),
                ('ct_frames_won', models.IntegerField(blank=True, null=True)),
                ('ct_career_prize_total', models.IntegerField(blank=True, null=True)),
                ('ct_total_titles', models.IntegerField(blank=True, null=True)),
                ('ct_ranking_titles', models.IntegerField(blank=True, null=True)),
                ('ct_finals_reached', models.IntegerField(blank=True, null=True)),
                ('ct_career_best_rank', models.IntegerField(blank=True, null=True)),
                ('ct_total_50plus', models.IntegerField(blank=True, null=True)),
                ('ct_total_centuries', models.IntegerField(blank=True, null=True)),
                ('titles_verified', models.BooleanField(null=True)),
                ('api_synced_at', models.DateTimeField(blank=True, null=True)),
                ('ct_synced_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='career_stats', to='oneFourSeven.player')),
            ],
            options={
                'verbose_name': 'Player Career Stats',
                'verbose_name_plural': 'Player Career Stats',
            },
        ),
    ]
