# Generated by Django 5.1.7 on 2026-04-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneFourSeven', '0021_playercareerstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifDedup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_match_id', models.CharField(db_index=True, max_length=64)),
                ('event_type', models.CharField(max_length=16)),
                ('sent_date', models.DateField(db_index=True)),
            ],
            options={
                'verbose_name': 'Notification Dedup',
                'unique_together': {('api_match_id', 'event_type', 'sent_date')},
            },
        ),
    ]
