# Generated by Django 5.1.7 on 2026-05-15 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneFourSeven', '0022_notifdedup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreboardMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(db_index=True, max_length=64)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoreboard_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scoreboard Match',
                'verbose_name_plural': 'Scoreboard Matches',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'match_id')},
            },
        ),
    ]
