# Generated by Django 5.1.7 on 2026-07-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneFourSeven', '0024_user_favorites_and_device_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetoken',
            name='favorite_match_db_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='userfavorite',
            name='favorite_match_db_ids',
            field=models.JSONField(default=list),
        ),
    ]
