# Generated by Django 5.1.7 on 2026-09-14 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneFourSeven', '0025_devicetoken_favorite_match_db_ids_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerBestBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reds_count', models.IntegerField()),
                ('best_break', models.IntegerField()),
                ('achieved_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_breaks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Player Best Break',
                'verbose_name_plural': 'Player Best Breaks',
                'ordering': ['reds_count'],
                'unique_together': {('user', 'reds_count')},
            },
        ),
    ]
