# Generated by Django 5.1.7 on 2026-09-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneFourSeven', '0026_playerbestbreak'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerbestbreak',
            name='frame_time_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerbestbreak',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
