# Generated by Django 5.1.7 on 2026-09-17 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneFourSeven', '0027_playerbestbreak_timing_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakTimingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_value', models.IntegerField()),
                ('duration_seconds', models.IntegerField()),
                ('mode', models.CharField(choices=[('match', 'Match'), ('unlimited', 'Unlimited')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_timings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Break Timing Record',
                'verbose_name_plural': 'Break Timing Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
