[providers]
python = "3.12"

[variables]
NIXPACKS_PYTHON_VERSION = "3.12"

[phases.setup]
nixPkgs = ['python312', 'bash', 'curl']

[phases.install]
cmds = [
    'python -m venv --copies /opt/venv',
    '. /opt/venv/bin/activate && pip install -r requirements.txt'
]

[phases.build]
cmds = [
    'chmod +x start_railway.sh'
]

[start]
cmd = 'python railway_start.py'