[services.web]
build.builder = "nixpacks"
deploy.startCommand = "cd maxBreak && python manage.py runserver 0.0.0.0:$PORT"

[services.worker]
build.builder = "nixpacks"
deploy.startCommand = "cd maxBreak && python manage.py auto_live_monitor"