// app/match/styles.ts
import { StyleSheet } from 'react-native';

export const createMatchStyles = (colors: any) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  centerContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  loadingText: {
    marginTop: 12,
    fontSize: 16,
    fontFamily: 'PoppinsRegular',
    color: colors.textSecondary,
    textAlign: 'center',
  },
  retryButton: {
    marginTop: 16,
    paddingHorizontal: 24,
    paddingVertical: 12,
    backgroundColor: colors.primary,
    borderRadius: 8,
  },
  retryText: {
    fontSize: 14,
    fontFamily: 'PoppinsSemiBold',
    color: colors.textPrimary,
  },
  shareButton: {
    padding: 8,
  },
  scoreHeader: {
    margin: 16,
    padding: 20,
    backgroundColor: colors.cardBackground,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.cardBorder,
  },
  scoreContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  playerContainer: {
    flex: 1,
    alignItems: 'center',
  },
  playerName: {
    fontSize: 16,
    fontFamily: 'PoppinsSemiBold',
    color: colors.textPrimary,
    textAlign: 'center',
    marginBottom: 8,
  },
  player1: {
    textAlign: 'left',
  },
  player2: {
    textAlign: 'right',
  },
  playerScore: {
    fontSize: 32,
    fontFamily: 'PoppinsBold',
    color: colors.primary,
  },
  winnerScore: {
    color: colors.success,
  },
  vsContainer: {
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  vsText: {
    fontSize: 14,
    fontFamily: 'PoppinsBold',
    color: colors.textSecondary,
    marginTop: 8,
  },
  tabContainer: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    marginBottom: 16,
  },
  tabButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    marginHorizontal: 4,
    borderRadius: 12,
    backgroundColor: colors.filterButton,
  },
  tabButtonActive: {
    backgroundColor: colors.filterButtonActive,
  },
  tabText: {
    fontSize: 12,
    fontFamily: 'PoppinsMedium',
    color: colors.textSecondary,
    marginLeft: 6,
  },
  tabTextActive: {
    color: colors.primary,
    fontFamily: 'PoppinsSemiBold',
  },
  contentContainer: {
    flex: 1,
    paddingHorizontal: 16,
  },
  statusCard: {
    padding: 16,
    marginBottom: 16,
    marginHorizontal: 16,
    backgroundColor: colors.cardBackground,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.cardBorder,
  },
  statusHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  statusTitle: {
    fontSize: 18,
    fontFamily: 'PoppinsSemiBold',
    color: colors.textPrimary,
  },
  statusText: {
    fontSize: 14,
    fontFamily: 'PoppinsRegular',
    color: colors.textSecondary,
    marginBottom: 16,
  },
  infoCard: {
    padding: 16,
    marginBottom: 16,
    marginHorizontal: 16,
    backgroundColor: colors.cardBackground,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.cardBorder,
  },
  infoHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  infoTitle: {
    fontSize: 16,
    fontFamily: 'PoppinsSemiBold',
    color: colors.textPrimary,
    marginLeft: 8,
  },
  infoText: {
    fontSize: 14,
    fontFamily: 'PoppinsRegular',
    color: colors.textSecondary,
  },
  sessionText: {
    fontSize: 14,
    fontFamily: 'PoppinsRegular',
    color: colors.textSecondary,
    marginBottom: 4,
  },
  framesContainer: {
    flex: 1,
  },
  framesTitle: {
    fontSize: 18,
    fontFamily: 'PoppinsSemiBold',
    color: colors.textPrimary,
    marginBottom: 16,
    textAlign: 'center',
  },
  framesGrid: {
    paddingBottom: 20,
  },
  frameCard: {
    margin: 4,
    padding: 12,
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 167, 38, 0.2)',
  },
  frameHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  frameNumber: {
    fontSize: 12,
    fontFamily: 'PoppinsSemiBold',
    color: '#9CA3AF',
  },
  frameScores: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  frameScore: {
    fontSize: 16,
    fontFamily: 'PoppinsBold',
    color: '#FFFFFF',
  },
  winningScore: {
    color: '#4CAF50',
  },
  frameSeparator: {
    fontSize: 14,
    fontFamily: 'PoppinsRegular',
    color: '#9CA3AF',
    marginHorizontal: 8,
  },
  frameIncomplete: {
    fontSize: 12,
    fontFamily: 'PoppinsRegular',
    color: '#9CA3AF',
    textAlign: 'center',
    fontStyle: 'italic',
  },
  frameBreaks: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 4,
  },
  frameBreak: {
    fontSize: 10,
    fontFamily: 'PoppinsMedium',
    color: '#9CA3AF',
    marginHorizontal: 2,
  },
  winningBreak: {
    color: '#4CAF50',
    fontFamily: 'PoppinsSemiBold',
  },
  statsCard: {
    padding: 16,
    marginBottom: 16,
    marginHorizontal: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 167, 38, 0.2)',
  },
  statsTitle: {
    fontSize: 18,
    fontFamily: 'PoppinsSemiBold',
    color: '#FFFFFF',
    marginBottom: 16,
  },
  statRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  statLabel: {
    fontSize: 14,
    fontFamily: 'PoppinsRegular',
    color: '#9CA3AF',
  },
  statValue: {
    fontSize: 14,
    fontFamily: 'PoppinsSemiBold',
    color: '#FFFFFF',
  },
  predictionCard: {
    padding: 16,
    marginBottom: 16,
    marginHorizontal: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 167, 38, 0.2)',
  },
  predictionTitle: {
    fontSize: 16,
    fontFamily: 'PoppinsSemiBold',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: 16,
  },
  predictionButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  predictionButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginHorizontal: 8,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  predictionButtonSelected: {
    backgroundColor: 'rgba(255, 167, 38, 0.2)',
    borderColor: '#FFA726',
  },
  predictionButtonText: {
    fontSize: 14,
    fontFamily: 'PoppinsSemiBold',
    color: '#9CA3AF',
    textAlign: 'center',
  },
  predictionButtonTextSelected: {
    color: '#FFA726',
  },
  h2hCard: {
    padding: 16,
    marginBottom: 16,
    marginHorizontal: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 167, 38, 0.2)',
  },
  h2hTitle: {
    fontSize: 18,
    fontFamily: 'PoppinsSemiBold',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: 8,
  },
  h2hSubtitle: {
    fontSize: 14,
    fontFamily: 'PoppinsRegular',
    color: '#9CA3AF',
    textAlign: 'center',
    marginBottom: 20,
  },
  h2hStats: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 20,
  },
  h2hStatItem: {
    alignItems: 'center',
  },
  h2hStatNumber: {
    fontSize: 20,
    fontFamily: 'PoppinsBold',
    color: '#FFA726',
    marginBottom: 4,
  },
  h2hStatLabel: {
    fontSize: 12,
    fontFamily: 'PoppinsRegular',
    color: '#9CA3AF',
    textAlign: 'center',
  },
  h2hLoading: {
    alignItems: 'center',
    paddingVertical: 40,
  },
  h2hLoadingText: {
    fontSize: 14,
    fontFamily: 'PoppinsRegular',
    color: '#9CA3AF',
    marginTop: 12,
  },
  h2hDetails: {
    marginTop: 20,
  },
  h2hDetailsTitle: {
    fontSize: 16,
    fontFamily: 'PoppinsSemiBold',
    color: '#FFFFFF',
    marginBottom: 16,
    textAlign: 'center',
  },
  h2hPlayersContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  h2hPlayerStat: {
    flex: 1,
    alignItems: 'center',
  },
  h2hPlayerName: {
    fontSize: 14,
    fontFamily: 'PoppinsSemiBold',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: 8,
  },
  h2hPlayerWins: {
    fontSize: 16,
    fontFamily: 'PoppinsBold',
    color: '#4CAF50',
    marginBottom: 4,
  },
  h2hPlayerPercentage: {
    fontSize: 12,
    fontFamily: 'PoppinsRegular',
    color: '#9CA3AF',
  },
  h2hVs: {
    paddingHorizontal: 20,
  },
  h2hVsText: {
    fontSize: 12,
    fontFamily: 'PoppinsBold',
    color: '#9CA3AF',
  },
  h2hEmpty: {
    alignItems: 'center',
    paddingVertical: 40,
  },
  h2hEmptyText: {
    fontSize: 16,
    fontFamily: 'PoppinsRegular',
    color: '#9CA3AF',
    textAlign: 'center',
    marginTop: 12,
  },
  h2hEmptySubtext: {
    fontSize: 14,
    fontFamily: 'PoppinsRegular',
    color: '#9CA3AF',
    textAlign: 'center',
    marginTop: 8,
    fontStyle: 'italic',
  },
  frameStatsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 16,
  },
  frameStatColumn: {
    flex: 1,
    alignItems: 'center',
  },
  frameStatDivider: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  frameStatTitle: {
    fontSize: 14,
    fontFamily: 'PoppinsSemiBold',
    color: '#9CA3AF',
    marginBottom: 8,
  },
  frameStatNumber: {
    fontSize: 28,
    fontFamily: 'PoppinsBold',
    color: '#FFA726',
    marginBottom: 4,
  },
  frameStatLabel: {
    fontSize: 12,
    fontFamily: 'PoppinsRegular',
    color: '#9CA3AF',
  },
  frameStatVs: {
    fontSize: 16,
    fontFamily: 'PoppinsBold',
    color: colors.textSecondary,
  },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
  },
  emptyText: {
    fontSize: 16,
    fontFamily: 'PoppinsRegular',
    color: '#9CA3AF',
    textAlign: 'center',
    marginTop: 12,
  },
  emptySubtext: {
    fontSize: 14,
    fontFamily: 'PoppinsRegular',
    color: '#9CA3AF',
    textAlign: 'center',
    marginTop: 8,
    fontStyle: 'italic',
  },
});