#!/usr/bin/env bash
set -euo pipefail

# EAS Build runs this at the PRE_INSTALL_HOOK phase, before INSTALL_DEPENDENCIES
# and well before PREBUILD.
#
# ACTUAL ROOT CAUSE (found 2026-07-28): `eas build`/`eas update` archive and
# upload the LOCAL project directory as a tarball - they do NOT git clone on
# the remote builder. There is no .git in the remote workingdir at all (a
# `git clean -fdx` attempt here proved this the hard way: with no git repo to
# compare against, it treated every file as untracked and deleted the entire
# project, failing the build instantly). That means EAS was never the one
# reusing a stale directory - every "Created native directory | reusing
# /android" and every "up to date" node_modules install came from a stale
# android/ (and .expo/) directory that existed LOCALLY on this dev machine,
# gitignored so invisible to `git status`, silently archived and uploaded on
# every single build since whenever those directories were last generated by
# a local `expo prebuild`/`expo run:android`.
#
# This hook is a remote-side backstop in case any future build path (e.g. a
# GitHub-integrated build that DOES use a real git checkout) reintroduces the
# same class of bug. The actual fix for the CLI-triggered path is keeping
# these directories out of the local working tree - not something a build
# hook alone can guarantee.
echo "[eas-build-pre-install] Removing any pre-existing native/cache directories to force a clean CNG prebuild"
rm -rf android ios .expo
